// Generated by build_github_site.py - do not edit by hand.
const CACHE = 'joe-fae3e00ad7';
const SHELL = ['./', 'index.html', 'manifest.webmanifest',
  'apple-touch-icon.png', 'favicon-32.png', 'icon-192.png', 'icon-512.png'];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});

async function cachedMarked(key) {
  const hit = await caches.match(key);
  if (!hit) return null;
  const headers = new Headers(hit.headers);
  headers.set('X-From-Cache', '1');
  return new Response(await hit.blob(), {status: hit.status, statusText: hit.statusText, headers});
}

function store(key, res) {
  const copy = res.clone();
  caches.open(CACHE).then(c => c.put(key, copy));
}

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);

  if (url.origin === location.origin && /\/data\/[^/]+\.json$/.test(url.pathname)) {
    const key = url.origin + url.pathname;
    e.respondWith(fetch(req)
      .then(res => { if (res.ok) store(key, res); return res; })
      .catch(async () => (await cachedMarked(key)) || Response.error()));
    return;
  }

  if (url.hostname === 'fonts.googleapis.com' || url.hostname === 'fonts.gstatic.com') {
    e.respondWith(caches.match(req).then(hit => hit || fetch(req).then(res => {
      if (res.ok || res.type === 'opaque') store(req, res);
      return res;
    })));
    return;
  }

  if (url.origin === location.origin) {
    const key = req.mode === 'navigate' ? new URL('index.html', self.registration.scope).href : req;
    e.respondWith(caches.match(key, {ignoreSearch: true}).then(hit => {
      const net = fetch(req).then(res => { if (res.ok) store(key, res); return res; });
      if (hit) { e.waitUntil(net.catch(() => {})); return hit; }
      return net;
    }));
  }
});
